### ISSUE TITLE
Alternator not transferring enough FE

### ISSUE THREAD

**Issue by kattaroten** [mrh0/createaddition#27]
**Describe the bug**
The alternator seems unable to transfer more than ~205 FE/t at 256 RPM to IE connectors no matter what configs are. 

**To Reproduce**
attach a creative motor turned to 256 RPM to the alternator, attach any IE connector with any IE wire to any consumer of FE

**Additional context**
205 FE/t seems to be 1/20 of the expected output so maybe there is some sort of bug with FE/t vs FE/s?

- Mod version: 20210320b
- Forge version: 35.1.37
- Create version: 0.3

**Comment by mrh0** [comment]
Thanks for the report, fixed in 20210402a!

**Comment by Glowstonesword** [comment]
I am still having this issue as of version 20210517a; though the goggles say there is 3600FE/t being produced, it appears that only 408FE/t is being extracted by any source (direct connection to a RFTools powercell, connectors, or IE wires). No changes to any config setting seem to affect this.
